### ISSUE TITLE
Dashboards are not all loading when accessing them 

### ISSUE THREAD

**Issue by jguipi** [credativ/plutono#54]
When I open a dashboard, I sometimes encounter panels that are empty, lacking any data. 

<img width="736" alt="image" src="https://github.com/credativ/plutono/assets/11049349/9e3cd759-05f7-4a3c-b7fe-fec405dd3c36">

However, when I edit the panel and switch the visualization, the data reappears. Unfortunately, if I refresh the page, I have to repeat the same steps to view the data again.

**Step to temporarily solve the issues:**
1. Click on edit 
<img width="183" alt="image" src="https://github.com/credativ/plutono/assets/11049349/fe9e7f6b-000d-46e1-af7d-8f7108ad5161">

2. Change the visualization to anything else  
<img width="373" alt="image" src="https://github.com/credativ/plutono/assets/11049349/1fadde92-e04a-4fb9-9fae-1c0912129b01">

3. go back to the original visualization method and then the dashboard appear again 
<img width="727" alt="image" src="https://github.com/credativ/plutono/assets/11049349/a5c9b9f5-898e-4121-9d26-b9c0185ab848">

**Expected behavior :** 
- All pannels to load the first time a dashboard is access

**Extra information:**
- Plutono version : 7.5.24

**Comment by credativ-dar** [comment]
Lacking a way to reproduce this on our side, I unfortunately see no approach to fixing this. Do you see any pattern which might help us track this down, like a certain browser, certain dashboards or graphs, maybe particularly many graphs (which I don't have in my current test setup)? Also try checking your browsers Javascript console for errors when this occurs.
