### ISSUE TITLE
Support of the 'role_attribute_strict' option in generic OAuth configuration

### ISSUE THREAD

**Issue by swaykg** [credativ/plutono#56]
Currently, when no role is applied to a user in generic OAuth configuration, the user is authorized as a Viewer or the role specified by the 'auto_assign_org_role' option.

The '[role_attribute_strict](https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/generic-oauth/#configuration-options)' configuration option has been introduced in Grafana 8.x, that denies user access if no role or an invalid role is returned. 

Is there a possibility to add this feature for security purposes?

**Comment by ntap-nmarco** [comment]
I am sorry. We are currently not planning to backport that configuration option.
If this changes, we will reopen this issue. I ask for your understanding here.
